"""update_user_info

Revision ID: 1aa83f97a8d6
Revises: f8550fbad0ec
Create Date: 2018-12-23 20:33:34.112583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1aa83f97a8d6'
down_revision = 'f8550fbad0ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
