"""update_user_info

Revision ID: 1aa83f97a8d6
Revises: f8550fbad0ec
Create Date: 2018-12-23 20:33:34.112583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1aa83f97a8d6'
down_revision = 'f8550fbad0ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('about', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('address', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('city', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('country', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('firstname', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('lastname', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('postalcode', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'postalcode')
    op.drop_column('users', 'lastname')
    op.drop_column('users', 'firstname')
    op.drop_column('users', 'email')
    op.drop_column('users', 'country')
    op.drop_column('users', 'city')
    op.drop_column('users', 'address')
    op.drop_column('users', 'about')
    # ### end Alembic commands ###
