"""initial

Revision ID: 5a04d5c2a0ce
Revises: 
Create Date: 2018-12-15 15:57:05.691721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a04d5c2a0ce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('song',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('subtitle', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('ytplayer', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_song')),
    sa.UniqueConstraint('title', name=op.f('uq_song_title'))
    )
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tag'))
    )
    op.create_table('token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_token'))
    )
    op.create_table('limittrade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buy_token', sa.Text(), nullable=False),
    sa.Column('sell_token', sa.Text(), nullable=False),
    sa.Column('value', sa.Numeric(precision=28, scale=18), nullable=False),
    sa.Column('rate', sa.Numeric(precision=28, scale=18), nullable=False),
    sa.Column('buysell', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_limittrade_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_limittrade'))
    )
    op.create_table('lyric',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language', sa.Text(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['song_id'], ['song.id'], name=op.f('fk_lyric_song_id_song')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lyric'))
    )
    op.create_table('rewards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Numeric(precision=28, scale=18), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['token_id'], ['token.id'], name=op.f('fk_rewards_token_id_token')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rewards'))
    )
    op.create_table('tags',
    sa.Column('song_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['song_id'], ['song.id'], name=op.f('fk_tags_song_id_song')),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], name=op.f('fk_tags_tag_id_tag'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tags')
    op.drop_table('rewards')
    op.drop_table('lyric')
    op.drop_table('limittrade')
    op.drop_table('token')
    op.drop_table('tag')
    op.drop_table('song')
    # ### end Alembic commands ###
